# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basestation.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 892)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1371, 861))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.functionality = QtWidgets.QVBoxLayout()
        self.functionality.setObjectName("functionality")
        self.camera_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.camera_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.camera_label.setAlignment(QtCore.Qt.AlignCenter)
        self.camera_label.setObjectName("camera_label")
        self.functionality.addWidget(self.camera_label)
        self.user_tools = QtWidgets.QHBoxLayout()
        self.user_tools.setObjectName("user_tools")
        self.functionality.addLayout(self.user_tools)
        self.battery_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.battery_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.battery_label.setAlignment(QtCore.Qt.AlignCenter)
        self.battery_label.setObjectName("battery_label")
        self.functionality.addWidget(self.battery_label)
        self.battery_bar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.battery_bar.setProperty("value", 24)
        self.battery_bar.setObjectName("battery_bar")
        self.functionality.addWidget(self.battery_bar)
        self.battery_stats_layout = QtWidgets.QHBoxLayout()
        self.battery_stats_layout.setContentsMargins(-1, 0, -1, -1)
        self.battery_stats_layout.setObjectName("battery_stats_layout")
        self.voltage_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.voltage_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.voltage_label.setObjectName("voltage_label")
        self.battery_stats_layout.addWidget(self.voltage_label)
        self.current_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.current_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.current_label.setObjectName("current_label")
        self.battery_stats_layout.addWidget(self.current_label)
        self.temperature_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.temperature_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.temperature_label.setObjectName("temperature_label")
        self.battery_stats_layout.addWidget(self.temperature_label)
        self.functionality.addLayout(self.battery_stats_layout)
        self.neat_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.neat_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.neat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.neat_label.setObjectName("neat_label")
        self.functionality.addWidget(self.neat_label)
        self.cv_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.cv_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cv_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cv_label.setObjectName("cv_label")
        self.functionality.addWidget(self.cv_label)
        self.horizontalLayout.addLayout(self.functionality)
        self.maps_layout = QtWidgets.QVBoxLayout()
        self.maps_layout.setObjectName("maps_layout")
        self.gps_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.gps_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.gps_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gps_label.setObjectName("gps_label")
        self.maps_layout.addWidget(self.gps_label)
        self.gps_map = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.gps_map.setMaximumSize(QtCore.QSize(16777215, 400))
        self.gps_map.setObjectName("gps_map")
        self.maps_layout.addWidget(self.gps_map)
        self.coords_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.coords_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.coords_label.setAlignment(QtCore.Qt.AlignCenter)
        self.coords_label.setObjectName("coords_label")
        self.maps_layout.addWidget(self.coords_label)
        self.horizontalLayout.addLayout(self.maps_layout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SigSent Station"))
        self.camera_label.setText(_translate("MainWindow", "Camera Feed"))
        self.battery_label.setText(_translate("MainWindow", "Battery"))
        self.voltage_label.setText(_translate("MainWindow", "Voltage: _V"))
        self.current_label.setText(_translate("MainWindow", "Current: _A"))
        self.temperature_label.setText(_translate("MainWindow", "Temperature: _F"))
        self.neat_label.setText(_translate("MainWindow", "NEAT Output: Crutches Engaged"))
        self.cv_label.setText(_translate("MainWindow", "Pedestrian Detected: YES"))
        self.gps_label.setText(_translate("MainWindow", "GPS"))
        self.coords_label.setText(_translate("MainWindow", "Longitude: 83.77 Latitude: 42.12"))

