# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basestation.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 892)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1101, 861))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.functionality = QtWidgets.QVBoxLayout()
        self.functionality.setObjectName("functionality")
        self.camera_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.camera_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.camera_label.setAlignment(QtCore.Qt.AlignCenter)
        self.camera_label.setObjectName("camera_label")
        self.functionality.addWidget(self.camera_label)
        self.gps_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.gps_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.gps_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gps_label.setObjectName("gps_label")
        self.functionality.addWidget(self.gps_label)
        self.gps_map = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.gps_map.setObjectName("gps_map")
        self.functionality.addWidget(self.gps_map)
        self.coords_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.coords_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.coords_label.setAlignment(QtCore.Qt.AlignCenter)
        self.coords_label.setObjectName("coords_label")
        self.functionality.addWidget(self.coords_label)
        self.horizontalLayout.addLayout(self.functionality)
        self.diagnostics = QtWidgets.QVBoxLayout()
        self.diagnostics.setObjectName("diagnostics")
        self.battery_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.battery_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.battery_label.setAlignment(QtCore.Qt.AlignCenter)
        self.battery_label.setObjectName("battery_label")
        self.diagnostics.addWidget(self.battery_label)
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.diagnostics.addWidget(self.progressBar)
        self.servo_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.servo_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.servo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_label.setObjectName("servo_label")
        self.diagnostics.addWidget(self.servo_label)
        self.servo_table = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.servo_table.setRowCount(18)
        self.servo_table.setColumnCount(3)
        self.servo_table.setObjectName("servo_table")
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.servo_table.setItem(17, 2, item)
        self.diagnostics.addWidget(self.servo_table)
        self.neat_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.neat_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.neat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.neat_label.setObjectName("neat_label")
        self.diagnostics.addWidget(self.neat_label)
        self.cv_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.cv_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cv_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cv_label.setObjectName("cv_label")
        self.diagnostics.addWidget(self.cv_label)
        self.diagnostics.setStretch(0, 1)
        self.diagnostics.setStretch(1, 1)
        self.diagnostics.setStretch(2, 1)
        self.diagnostics.setStretch(3, 1)
        self.diagnostics.setStretch(4, 1)
        self.diagnostics.setStretch(5, 1)
        self.horizontalLayout.addLayout(self.diagnostics)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.camera_label.setText(_translate("MainWindow", "Camera Feed"))
        self.gps_label.setText(_translate("MainWindow", "GPS"))
        self.coords_label.setText(_translate("MainWindow", "Longitude: 83.77 Latitude: 42.12"))
        self.battery_label.setText(_translate("MainWindow", "Battery"))
        self.servo_label.setText(_translate("MainWindow", "Servo Positions"))
        item = self.servo_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Servo 1"))
        item = self.servo_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Servo 2"))
        item = self.servo_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Servo 3"))
        item = self.servo_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Servo 4"))
        item = self.servo_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Servo 5"))
        item = self.servo_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Servo 6"))
        item = self.servo_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Servo 7"))
        item = self.servo_table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Servo 8"))
        item = self.servo_table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Servo 9"))
        item = self.servo_table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Servo 10"))
        item = self.servo_table.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Servo 11"))
        item = self.servo_table.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Servo 12"))
        item = self.servo_table.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Servo 13"))
        item = self.servo_table.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "Servo 14"))
        item = self.servo_table.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "Servo 15"))
        item = self.servo_table.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "Servo 16"))
        item = self.servo_table.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "Servo 17"))
        item = self.servo_table.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "Servo 18"))
        item = self.servo_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Leg"))
        item = self.servo_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Joint"))
        item = self.servo_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Position"))
        __sortingEnabled = self.servo_table.isSortingEnabled()
        self.servo_table.setSortingEnabled(False)
        item = self.servo_table.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.servo_table.item(0, 1)
        item.setText(_translate("MainWindow", "1"))
        item = self.servo_table.item(0, 2)
        item.setText(_translate("MainWindow", "45"))
        item = self.servo_table.item(1, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.servo_table.item(1, 1)
        item.setText(_translate("MainWindow", "2"))
        item = self.servo_table.item(1, 2)
        item.setText(_translate("MainWindow", "15"))
        item = self.servo_table.item(2, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.servo_table.item(2, 1)
        item.setText(_translate("MainWindow", "3"))
        item = self.servo_table.item(2, 2)
        item.setText(_translate("MainWindow", "20"))
        item = self.servo_table.item(3, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.servo_table.item(3, 1)
        item.setText(_translate("MainWindow", "1"))
        item = self.servo_table.item(3, 2)
        item.setText(_translate("MainWindow", "45"))
        item = self.servo_table.item(4, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.servo_table.item(4, 1)
        item.setText(_translate("MainWindow", "2"))
        item = self.servo_table.item(4, 2)
        item.setText(_translate("MainWindow", "15"))
        item = self.servo_table.item(5, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.servo_table.item(5, 1)
        item.setText(_translate("MainWindow", "3"))
        item = self.servo_table.item(5, 2)
        item.setText(_translate("MainWindow", "20"))
        item = self.servo_table.item(6, 0)
        item.setText(_translate("MainWindow", "3"))
        item = self.servo_table.item(6, 1)
        item.setText(_translate("MainWindow", "1"))
        item = self.servo_table.item(6, 2)
        item.setText(_translate("MainWindow", "45"))
        item = self.servo_table.item(7, 0)
        item.setText(_translate("MainWindow", "3"))
        item = self.servo_table.item(7, 1)
        item.setText(_translate("MainWindow", "2"))
        item = self.servo_table.item(7, 2)
        item.setText(_translate("MainWindow", "15"))
        item = self.servo_table.item(8, 0)
        item.setText(_translate("MainWindow", "3"))
        item = self.servo_table.item(8, 1)
        item.setText(_translate("MainWindow", "3"))
        item = self.servo_table.item(8, 2)
        item.setText(_translate("MainWindow", "20"))
        item = self.servo_table.item(9, 0)
        item.setText(_translate("MainWindow", "4"))
        item = self.servo_table.item(9, 1)
        item.setText(_translate("MainWindow", "1"))
        item = self.servo_table.item(9, 2)
        item.setText(_translate("MainWindow", "45"))
        item = self.servo_table.item(10, 0)
        item.setText(_translate("MainWindow", "4"))
        item = self.servo_table.item(10, 1)
        item.setText(_translate("MainWindow", "2"))
        item = self.servo_table.item(10, 2)
        item.setText(_translate("MainWindow", "15"))
        item = self.servo_table.item(11, 0)
        item.setText(_translate("MainWindow", "4"))
        item = self.servo_table.item(11, 1)
        item.setText(_translate("MainWindow", "3"))
        item = self.servo_table.item(11, 2)
        item.setText(_translate("MainWindow", "20"))
        item = self.servo_table.item(12, 0)
        item.setText(_translate("MainWindow", "5"))
        item = self.servo_table.item(12, 1)
        item.setText(_translate("MainWindow", "1"))
        item = self.servo_table.item(12, 2)
        item.setText(_translate("MainWindow", "45"))
        item = self.servo_table.item(13, 0)
        item.setText(_translate("MainWindow", "5"))
        item = self.servo_table.item(13, 1)
        item.setText(_translate("MainWindow", "2"))
        item = self.servo_table.item(13, 2)
        item.setText(_translate("MainWindow", "15"))
        item = self.servo_table.item(14, 0)
        item.setText(_translate("MainWindow", "5"))
        item = self.servo_table.item(14, 1)
        item.setText(_translate("MainWindow", "3"))
        item = self.servo_table.item(14, 2)
        item.setText(_translate("MainWindow", "20"))
        item = self.servo_table.item(15, 0)
        item.setText(_translate("MainWindow", "6"))
        item = self.servo_table.item(15, 1)
        item.setText(_translate("MainWindow", "1"))
        item = self.servo_table.item(15, 2)
        item.setText(_translate("MainWindow", "45"))
        item = self.servo_table.item(16, 0)
        item.setText(_translate("MainWindow", "6"))
        item = self.servo_table.item(16, 1)
        item.setText(_translate("MainWindow", "2"))
        item = self.servo_table.item(16, 2)
        item.setText(_translate("MainWindow", "15"))
        item = self.servo_table.item(17, 0)
        item.setText(_translate("MainWindow", "6"))
        item = self.servo_table.item(17, 1)
        item.setText(_translate("MainWindow", "3"))
        item = self.servo_table.item(17, 2)
        item.setText(_translate("MainWindow", "20"))
        self.servo_table.setSortingEnabled(__sortingEnabled)
        self.neat_label.setText(_translate("MainWindow", "NEAT Output: Crutches Engaged"))
        self.cv_label.setText(_translate("MainWindow", "Pedestrian Detected: YES"))

